### ISSUE TITLE
Quiero ayudar a traducir toda la rom correctamente. I want to help translating

### ISSUE THREAD

**Issue by esansnewman** [ingbrzy/MA-XML-12-SPANISH#1]
quiero corregir varios errores de traducciones por mi cuenta
i want to correct some translation errors by mysleve

**Comment by Andrescity** [comment]
me uno también

**Comment by AngelToribio** [comment]
quisiera ayudar a corregir y añadir traducciones al español

**Comment by esansnewman** [comment]
quién quiera ayudar que me mande a mi correo esansnewman@gmail.com los siguiente datos:
versión de la rom (beta/estable), dispositivo, qué aplicación tiene algo sin traducir y una captura de pantalla
