### ISSUE TITLE
SEGURIDAD clear trash files

### ISSUE THREAD

**Issue by migel20** [ingbrzy/MA-XML-12-SPANISH#10]
APK: seguridad
Frase: clear trash files
Modelo: Mi9t
ROM: MIUI 12 20.5.21 weekly
![photo_2020-05-22_19-13-15](https://user-images.githubusercontent.com/65781428/82692655-67c55300-9c60-11ea-8050-324080ced806.jpg)
weekly

**Comment by nmercy-arg** [comment]
En la proxima release deberia estar traducido.

**Comment by nmercy-arg** [comment]
Traducido
