### ISSUE TITLE
Español (América) - Español(España)

### ISSUE THREAD

**Issue by texta84** [ingbrzy/MA-XML-12-SPANISH#100]
Estoy en el idioma Español(América) y muestra "Desactivado" pero si cambio a Español(España) muestra "No Activo", ahora viendo estos dos paquetes: `values-es-rUS/strings.xml` y `values-es/strings.xml` noto que hay mucha diferencia de cadenas pero fuera de eso es que las cadenas con nombres que inician con `miui_ringer_` solo están presentes en `values-es-rUS/strings.xml`  y no se si eso tenga algo que ver con que en el idioma Español(América) muestre "Desactivado" y no "No Activo". Tengo una pregunta ya que desconozco del tema, hay algún problema con el que los paquetes del idioma Español América y España sean iguales?

![Screenshot_2021-01-22-13-07-32-778_com android settings](https://user-images.githubusercontent.com/65029682/105538662-5c2b9f80-5cb9-11eb-95c2-fcf51e7d7dbb.png)
![Screenshot-2021-01-21-16-33-05-384-com-miui-home](https://user-images.githubusercontent.com/65029682/105538653-5930af00-5cb9-11eb-8fc6-2394c6012f20.png)
![América](https://user-images.githubusercontent.com/65029682/105538655-5afa7280-5cb9-11eb-9f20-7a41e5c5a598.png)
![España](https://user-images.githubusercontent.com/65029682/105538658-5b930900-5cb9-11eb-9808-49fe9d9e9de2.png)

**Comment by deivids84** [comment]
Español (América) no se actualiza.
