### ISSUE TITLE
Fallo de traducción en Brújula

### ISSUE THREAD

**Issue by MarMarAba** [ingbrzy/MA-XML-12-SPANISH#102]
Los puntos cardinales aparecen como:

norte
nordeste
E
SE
D (?)
SO
O
NO

**Comment by deivids84** [comment]
Corregido en 21.3.3. Algún fallo más? https://github.com/ingbrzy/MA-XML-12-SPANISH/commit/ee27727ec60c3dc4d8ec87a5ae33f90c1641bf15
