### ISSUE TITLE
Mala traducción en No molestar y Silenciar

### ISSUE THREAD

**Issue by Sergiote** [ingbrzy/MA-XML-12-SPANISH#104]
Modo No molestar y Silenciar. Mala traducción tanto el texto que te da cómo en las propias opciones del menú de volúmen. Español españa.

![Screenshot_2021-04-22-13-27-29-100_com android chrome~2](https://user-images.githubusercontent.com/83012193/115707672-5eac9c80-a36f-11eb-8c4b-8d437517d813.jpg)
![Screenshot_2021-04-22-13-27-25-390_com android chrome~3](https://user-images.githubusercontent.com/83012193/115707675-5f453300-a36f-11eb-85d1-0de2c159b867.jpg)
![Screenshot_2021-04-22-13-27-16-169_com android chrome~2](https://user-images.githubusercontent.com/83012193/115707678-5f453300-a36f-11eb-8fd1-59a7c31ff4ad.jpg)
![Screenshot_2021-04-22-13-27-19-854_com android chrome~2](https://user-images.githubusercontent.com/83012193/115707680-5fddc980-a36f-11eb-90fd-59eee88b7f44.jpg)
![Screenshot_2021-04-22-13-32-52-300_com android chrome~2](https://user-images.githubusercontent.com/83012193/115707681-5fddc980-a36f-11eb-8c52-76a0b6a7dfb8.jpg)

**Comment by deivids84** [comment]
En nuevas versiones ya está corregido
