### ISSUE TITLE
Falli de traducción Pantalla siempre activa y pantalla de bloqueo

### ISSUE THREAD

**Issue by Sergiote** [ingbrzy/MA-XML-12-SPANISH#105]
Fallo de traducción en Ajustes - Pantalla siempre activa y pantalla de bloqueo. Español España.

![Screenshot_2021-04-22-13-35-44-422_com android settings~2](https://user-images.githubusercontent.com/83012193/115708146-eb575a80-a36f-11eb-94e9-3bfab3a2fb36.jpg)

**Comment by deivids84** [comment]
En nuevas versiones ya está corregido
