### ISSUE TITLE
Posible fallo de traducción en Sonido y Vibración

### ISSUE THREAD

**Issue by Sergiote** [ingbrzy/MA-XML-12-SPANISH#106]
Ajustes - Sonido y Vibración, posible fallo de traducción.

Al igual que en roms oficiales de Xiaomi debería ser Tono de llamada y no Tono de Alarma, da a confusión con el Tono de Alarma de las alarmas del móvil.
Español España.
Mi 9T estable miui 12.1.2 android 11

![Screenshot_2021-04-22-13-41-38-684_com android settings~2](https://user-images.githubusercontent.com/83012193/115708831-c1526800-a370-11eb-86f5-5d6f96be7bc8.jpg)

**Comment by deivids84** [comment]
Corregido
