### ISSUE TITLE
Fallo de traducción

### ISSUE THREAD

**Issue by Sergiote** [ingbrzy/MA-XML-12-SPANISH#107]
Fallo de traducción en Ajustes - Batería y rendimiento - Ajustes (rueda dentada arriba a la derecha) -Ahorro de batería y también el ultra ahorro de batería.
Español España

Gracias por tu trabajo, me gusta ayudar en lo que puedo.
Mi 9T estable miui 12.1.2 android 11

![Screenshot_2021-04-22-15-09-45-635_com miui securitycenter~2](https://user-images.githubusercontent.com/83012193/115720444-5fe4c600-a37d-11eb-824c-c9227a4b2cc1.jpg)
![Screenshot_2021-04-22-15-09-32-112_com miui securitycenter~2](https://user-images.githubusercontent.com/83012193/115720451-6115f300-a37d-11eb-9278-32a293c86c6a.jpg)

**Comment by deivids84** [comment]
En la versión estable 12.1.2 faltaban muchas traducciones. En la versión 12.5 ya está todo traducido.
