### ISSUE TITLE
android.process.media continúa fallando

### ISSUE THREAD

**Issue by GhostlyName** [ingbrzy/MA-XML-12-SPANISH#108]
Al ingresar una cuenta institucional al dispositivo con la ROM pide descargar Android Devices Policy lo cual no es raro pero al momento de que el dispositivo configura el perfil de trabajo aparecía el error **android.process.media** constantemente siendo molesto en cualquier momento. Cuando me apareció por primera vez no me dejaba eliminar la cuenta y tuve que formatear pero al hacer lo antes mencionado salía otra vez el error. 
Vi en varios videos y en varias paginas como se solucionaba y cual era la causa, aplique los métodos para solucionar el inconveniente pero nada, incluso hizo que la Google Play me saliera error de servidor.

Xiaomi Redmi S2 Miui 12.0.4 Android 9
![Screenshot_2021-04-28-21-35-32-027_com google android apps work clouddpc](https://user-images.githubusercontent.com/64048635/116501480-78217d00-a876-11eb-8b84-374238433a2c.jpg)

**Comment by deivids84** [comment]
¿Solo pasa con el idioma Español?

**Comment by GhostlyName** [comment]
> ¿Solo pasa con el idioma Español?
Cambie el idioma a ingles e igual.
