### ISSUE TITLE
Fallo de traducción Español España

### ISSUE THREAD

**Issue by Sergiote** [ingbrzy/MA-XML-12-SPANISH#109]
Fallo de traducción en idioma Español España
Xiaomi Mi 9T Xiaomi.eu Weekly 12.6 21.5.20 beta

El texto que indica que el modo de pantalla está bloqueado en modo horizontal no está traducido.

![Screenshot_2021-05-23-21-23-57-928_com facebook games](https://user-images.githubusercontent.com/83012193/119273975-d0e1fc80-bc0d-11eb-9158-37713a88d908.jpg)

**Comment by deivids84** [comment]
![IMG_20210524_095601](https://user-images.githubusercontent.com/13929105/119315683-674a0880-bc76-11eb-9c97-e2009527f33f.jpg)
La línea fue publicada y traducida el pasado día 19. En la próxima beta estará incluida
