### ISSUE TITLE
Intensidad de modo lectura MIUI 12.5.1 HMNOTE8

### ISSUE THREAD

**Issue by JUANX0799** [ingbrzy/MA-XML-12-SPANISH#112]
el modo lectura no esta regulnando la intensidad y permace constante adicionalmente esta sobredimencionando los cuadros de texto que no estan adaptados para la longitud de los textos

**Comment by deivids84** [comment]
Aquí solo errores de traducción. Por fallos de la ROM en la sección de bugs de https://www.xiaomi.eu
