### ISSUE TITLE
problemas con la conexion de wifi y multitarea  HMNOTE8 MIUI12.5.1

### ISSUE THREAD

**Issue by JUANX0799** [ingbrzy/MA-XML-12-SPANISH#113]
al utilizar aplicaciones en segundo plano-primer plano que utilicen la red opta por cerrar una de las aplicaciones o reducir la calidad de conexion a la red aunque se esten realizando actividad que consuman pocos recursos ya sea en segundo y en primer plano o ambas  al mismo tiempo, ya sea esten bloqueadas para no cerrarse en el menu.

he probado esto con chrome, soundwire, instagram, whatsapp, youtube, unified remote, samsung internet, miui browser mezclando las de carga pesada con ligera y ligeras con ligeras(sin solucion)

adicional funciona bien con el modo cast de miu compartiendo videos pero con el mismo problema de no poder utilizar dos apliciones al mismo tiempo aunque este activado el asistente de sonido y se utilicen lo ajustes avanzados de proyeccion-ventana flotante(se cierra)

**Comment by deivids84** [comment]
Aquí solo errores de traducción, por fallos de la ROM en la sección de bugs de https://www.xiaomi.eu
