### ISSUE TITLE
Modo pantanlla completa no funcionando HMNOTE8 MIUI12.5.1

### ISSUE THREAD

**Issue by JUANX0799** [ingbrzy/MA-XML-12-SPANISH#114]
al utilizar la pantalla completa en modo horizontal permacen bordes negros y fallan las animaciones al volver al modo vertical(se parte en dos) en culaquier aplicacion y el teclado permance muy bajo aun con la maxima altura permitida y tampoco llena la pantalla en modo horizontal al typear

**Comment by deivids84** [comment]
Aquí solo errores de traducción, por fallos de la ROM en la sección de bugs de https://www.xiaomi.eu
