### ISSUE TITLE
Redmi 9T - Lag para abrir aplicaciones y durante el uso general 

### ISSUE THREAD

**Issue by jubilostudios** [ingbrzy/MA-XML-12-SPANISH#116]
Redmi 9T (LIME) V12.5.5 estable - Lag para abrir aplicaciones y durante el uso general.

Las aplicaciones reaccionan de forma lenta, demora mucho en abrir aplicaciones simples como configuración. El dispositivo se calienta mucho del lado superior izquierdo .

Ninguno de estos problemas están presentes en la versión estable y oficial de Xiaomi.

**Comment by ingbrzy** [comment]
not a translation issue
