### ISSUE TITLE
Redmi 9T (LIME) - Super wallpapers no funcionan 

### ISSUE THREAD

**Issue by jubilostudios** [ingbrzy/MA-XML-12-SPANISH#117]
Redmi 9T (LIME) V12.5.5 estable.

Solo funcionan los super wallpapers de "Cumbres Nevadas" y "Geometrías"

El restante no responde. La única forma de hacerlos funcionar es descargando de forma no oficial la APK correspondiente a cada super wallpapers.

**Comment by ingbrzy** [comment]
not a translation issue
