### ISSUE TITLE
Redmi 9T (LIME) - Descarga de Super Wallpapers no funcionan

### ISSUE THREAD

**Issue by jubilostudios** [ingbrzy/MA-XML-12-SPANISH#118]
Redmi 9T (LIME) V12.5.5 estable. Al intentar tocar el icono de descarga de cada wallpaper (una vez desinstalando los) la aplicación no hace nada.

Es como si el botón no tuviera ninguna función , no descarga y responde.

**Comment by ingbrzy** [comment]
not a translation issue
