### ISSUE TITLE
Error en la traducción 20.6.11 Mi 9T

### ISSUE THREAD

**Issue by Davidjarod11** [ingbrzy/MA-XML-12-SPANISH#15]
Hola , en el centro de control cuando se enciende un toogle debería decir "Encendido" pero dice "En" y también falta la traducción del toggle del Modo oscuro, también hay un error en la traducción en los ajustes de contraseña y seguridad, gracias por su gran trabajo con esta ROM.
![IMG_20200610_202133](https://user-images.githubusercontent.com/47721967/84334706-a318ba80-ab58-11ea-9a92-4d43bbfe72b9.jpg)
![IMG_20200611_150624](https://user-images.githubusercontent.com/47721967/84434189-30115180-abf5-11ea-8f54-ad6f8d80cb63.jpg)

**Comment by Oxnap** [comment]
Arreglado en la próxima versión
