### ISSUE TITLE
App cámara MI 9T 20.6.11 weekly

### ISSUE THREAD

**Issue by yeryhs** [ingbrzy/MA-XML-12-SPANISH#16]
Algunas cosas sin traducir en la app de cámara:

- Vista "Más" (carrusel abajo)
- Opción "Documentos" en la vista 'More'
- Opción "Clonar" en la vista 'More'
- Opción "Editar" en la vista 'More'

![Screenshot_2020-06-16-11-20-53-206_com android camera](https://user-images.githubusercontent.com/66997975/84758417-b945d100-afc5-11ea-8147-162c665ad211.jpg)

**Comment by Oxnap** [comment]
Corregido, en la próxima versión se verán los cambios
