### ISSUE TITLE
Estadísticas de bateria en MI 9T 20.6.11 weekly

### ISSUE THREAD

**Issue by yeryhs** [ingbrzy/MA-XML-12-SPANISH#17]
- Detalles de consumo
- Consumo total
- % consumo total

![Screenshot_2020-06-16-11-21-39-269_com miui securitycenter](https://user-images.githubusercontent.com/66997975/84758799-35d8af80-afc6-11ea-8da1-160ceec3eaba.jpg)

- Gráfico de consumo
- Activo
- En reposo

![Screenshot_2020-06-16-11-21-35-743_com miui securitycenter](https://user-images.githubusercontent.com/66997975/84758844-42f59e80-afc6-11ea-99e7-2be95c3c6ef4.jpg)

**Comment by Oxnap** [comment]
Corregido en la próxima versión
