### ISSUE TITLE
Falla de Tarjeta SIM. REdmi Note 7

### ISSUE THREAD

**Issue by Dreyte** [ingbrzy/MA-XML-12-SPANISH#19]
Al instalar la rom, no hay forma de que se detecte mi Tarjeta Sim. PRobando con diferentes tarjetas y en los diferentes puertos de la Dual sim nunca los reconoce

**Comment by Oxnap** [comment]
Hola! Aunque entiendo tu problema, este repositorio es para la traducción de la ROM, más que para el funcionamiento. Para obtener ayuda, debes publicar en el Foro Bugs de xiaomi.eu, describiendo el problema en inglés.
Saludos

**Comment by paul911** [comment]
> Al instalar la rom, no hay forma de que se detecte mi Tarjeta Sim. PRobando con diferentes tarjetas y en los diferentes puertos de la Dual sim nunca los reconoce
