### ISSUE TITLE
Fallo traducción Estadísticas batería Mi10Pro Stable 12.0.3

### ISSUE THREAD

**Issue by rube13** [ingbrzy/MA-XML-12-SPANISH#30]
**La aplicación**: Ajustes > Batería > Estadísticas uso de la batería
**La frase que está la frase sin traducir o está mal escrita**: Indicada en la captura de pantalla
**El modelo de tú dispositivo**: Mi10Pro
**Versión de la ROM** (Stable/Weekly, y número de versión): Stable 12.0.3

![IMG_20200731_133622](https://user-images.githubusercontent.com/69046280/89045190-66449500-d34b-11ea-8af3-d5c652f47d2b.jpg)

**Comment by Oxnap** [comment]
Hola! Esta frase ya ha sido traducida. Se verá reflejada en el próximo release. Saludos!
