### ISSUE TITLE
Fallo traducción App Vault Mi10Pro Stable 12.0.3

### ISSUE THREAD

**Issue by rube13** [ingbrzy/MA-XML-12-SPANISH#33]
**La aplicación**: App Vault
**La frase que está la frase sin traducir o está mal escrita**: Indicada en la captura de pantalla
**El modelo de tú dispositivo**: Mi10Pro
**Versión de la ROM** (Stable/Weekly, y número de versión): Stable 12.0.3

![IMG_20200731_133507](https://user-images.githubusercontent.com/69046280/89045630-1ca87a00-d34c-11ea-9dc7-cdd7c6e51eec.jpg)

**Comment by Oxnap** [comment]
Al parecer, esta aplicación no viene incluida por defecto dentro de la ROM, por lo que la traducción no la podemos realizar.
