### ISSUE TITLE
Fallo traducción Almacenamiento Mi10Pro Stable 12.0.3

### ISSUE THREAD

**Issue by rube13** [ingbrzy/MA-XML-12-SPANISH#39]
**La aplicación**: Ajustes > Almacenamiento
**La frase que está la frase sin traducir o está mal escrita**: Indicada en la captura de pantalla
**El modelo de tú dispositivo**: Mi10Pro
**Versión de la ROM** (Stable/Weekly, y número de versión): Stable 12.0.3

![Screenshot_2020-07-30-16-46-20-595_com miui securitycenter](https://user-images.githubusercontent.com/69046280/89047001-0d2a3080-d34e-11ea-9f1d-539d837b49e6.jpg)

**Comment by Oxnap** [comment]
Gracias por las sugerencias @rube13 , favor seguir comunicando cualquier traducción errónea o faltante
