### ISSUE TITLE
Fallo de traducciones en algunas apps Mi 9T Weekly 20.8.6

### ISSUE THREAD

**Issue by Priplio** [ingbrzy/MA-XML-12-SPANISH#52]
Hola, he encontrado fallos de traducción en algunas aplicaciones, de antemano doy gracias por tu trabajo 👍 

La aplicación: App Vault
La frase que está la frase sin traducir o está mal escrita: Tiempo en el calendario (aparece en la captura)
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.6

![InkedScreenshot_2020-08-10-08-46-47-817_com miui home_LI](https://user-images.githubusercontent.com/69436116/89794039-240a1900-daec-11ea-940b-f3d077fdd0d5.jpg)

La aplicación: IU del sistema?
La frase que está la frase sin traducir o está mal escrita: Brillo automático encendido
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.6

![IMG_20200809_154619](https://user-images.githubusercontent.com/69436116/89792895-c88b5b80-daea-11ea-8456-1da11d6a77b0.jpg)

La aplicación: Galeria
La frase que está la frase sin traducir o está mal escrita: Falta de traducción en algunas partes, señaladas en las capturas
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.6
![InkedInkedScreenshot_2020-08-10-09-02-47-352_com miui gallery_LI](https://user-images.githubusercontent.com/69436116/89793962-0f2d8580-daec-11ea-9c7a-f4c4f893b545.jpg)

![InkedScreenshot_2020-08-10-09-24-43-111_com miui gallery_LI](https://user-images.githubusercontent.com/69436116/89794264-6cc1d200-daec-11ea-99e0-dad2bba8eebc.jpg)

La aplicación: Configuración
La frase que está la frase sin traducir o está mal escrita: El título del menú de temas esta en inglés
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.6

![InkedScreenshot_2020-08-09-15-35-09-294_com android thememanager_LI](https://user-images.githubusercontent.com/69436116/89795795-70565880-daee-11ea-880a-70a4165a0cba.jpg)

La aplicación: Configuración
La frase que está la frase sin traducir o está mal escrita: Los titulos de accesibilidad no estan traducidos
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.6

![IMG_20200810_095334](https://user-images.githubusercontent.com/69436116/89796748-9f20fe80-daef-11ea-8057-84c5e45c9a9a.jpg)

Gracias y perdón por poner tantos.

**Comment by Oxnap** [comment]
Gracias por las sugerencias, las acabamos de corregir. Si encuentras más, avísanos. 👍
