### ISSUE TITLE
Faltas de traducción Mi 9T Weekly 20.8.20

### ISSUE THREAD

**Issue by Priplio** [ingbrzy/MA-XML-12-SPANISH#68]
Hola en esta versión he encontrado algunas nuevas faltas de traducción en múltiples apps.
Gracias 👍 
La aplicación: Temas
La frase que está la frase sin traducir o está mal escrita: Faltas en capturas.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20
![IMG_20200820_150442](https://user-images.githubusercontent.com/69436116/90897256-7966e580-e38a-11ea-82cc-b0c6621725ec.jpg)
![IMG_20200820_150512](https://user-images.githubusercontent.com/69436116/90897258-79ff7c00-e38a-11ea-8c2d-db55b775c43c.jpg)
![IMG_20200820_150538](https://user-images.githubusercontent.com/69436116/90897259-79ff7c00-e38a-11ea-9105-a2b13fd73585.jpg)
![IMG_20200820_150424](https://user-images.githubusercontent.com/69436116/90897261-7a981280-e38a-11ea-901b-d3c9398678ad.jpg)

La aplicación: Galeria
La frase que está la frase sin traducir o está mal escrita: Faltas en la captura.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20
![IMG_20200820_150143](https://user-images.githubusercontent.com/69436116/90897382-a7e4c080-e38a-11ea-807c-607f46273abb.jpg)
![IMG_20200820_151926](https://user-images.githubusercontent.com/69436116/90897428-ba5efa00-e38a-11ea-89fa-6e21fb09f468.jpg)

La aplicación: Calendario
La frase que está la frase sin traducir o está mal escrita: Faltas en la captura.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20

![IMG_20200820_150223](https://user-images.githubusercontent.com/69436116/90897626-0b6eee00-e38b-11ea-9d8f-ff6e79d465f8.jpg)
![IMG_20200820_150248](https://user-images.githubusercontent.com/69436116/90897629-0c078480-e38b-11ea-9986-31889bc68670.jpg)

La aplicación: Xiaomi Cloud
La frase que está la frase sin traducir o está mal escrita: Faltas en la captura.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20

![IMG_20200820_150321](https://user-images.githubusercontent.com/69436116/90897746-36594200-e38b-11ea-854b-a8c1026bbd98.jpg)
![IMG_20200821_205327](https://user-images.githubusercontent.com/69436116/90946242-96360400-e3f0-11ea-9357-9ef0aa7aadbb.jpg)

La aplicación: System UI
La frase que está la frase sin traducir o está mal escrita: Faltas en la captura.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20

![IMG_20200820_150204](https://user-images.githubusercontent.com/69436116/90898234-f3e43500-e38b-11ea-9e27-2572ec701912.jpg)

La aplicación: Intalador de paquetes
La frase que está la frase sin traducir o está mal escrita: Faltas en la captura.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20

![IMG_20200820_151702](https://user-images.githubusercontent.com/69436116/90898297-0c544f80-e38c-11ea-86a7-422c808df6ba.jpg)

La aplicación: Seguridad
La frase que está la frase sin traducir o está mal escrita: Faltas en la captura.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20

![Screenshot_2020-08-21-08-37-23-789_com miui securitycenter](https://user-images.githubusercontent.com/69436116/90898503-55a49f00-e38c-11ea-948a-f248e09d4965.jpg)

La aplicación: Configuración
La frase que está la frase sin traducir o está mal escrita: Falta en la captura, esta ya la habia reportado, pero la vuelvo a poner.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20

![Screenshot_2020-08-20-14-52-51-253_com miui securitycenter](https://user-images.githubusercontent.com/69436116/90898678-85ec3d80-e38c-11ea-91c1-077c5ddf1a72.jpg)
![Screenshot_2020-08-20-14-52-54-234_com miui securitycenter](https://user-images.githubusercontent.com/69436116/90898681-871d6a80-e38c-11ea-8e5f-535d0dfe5f7e.jpg)

La aplicación: Seguridad
La frase que está la frase sin traducir o está mal escrita: Faltas en capturas.
El modelo de tú dispositivo: Mi 9T
Versión de la ROM (Stable/Weekly, y número de versión): Weekly 20.8.20
![IMG_20200821_204754](https://user-images.githubusercontent.com/69436116/90946140-c7fa9b00-e3ef-11ea-865c-7a60a0f171d9.jpg)

Gracias :)

**Comment by Alemancillo** [comment]
Translated in #75 
Can be closed
