### ISSUE TITLE
Falta de traducción en app de salud Mi 9T Weekly 2.8.20

### ISSUE THREAD

**Issue by Priplio** [ingbrzy/MA-XML-12-SPANISH#69]
La app: Salud
Sin traducir: Hay una buena parte la app de salud sin traducir, lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.8.20
![Screenshot_2020-08-21-19-25-01-742_com mi health](https://user-images.githubusercontent.com/69436116/90946326-64716d00-e3f1-11ea-841f-566712646eea.jpg)
![IMG_20200821_205230](https://user-images.githubusercontent.com/69436116/90946327-650a0380-e3f1-11ea-9f25-18a3e178af67.jpg)
![IMG_20200821_205722](https://user-images.githubusercontent.com/69436116/90946328-663b3080-e3f1-11ea-8e4b-ef9c11e8f88f.jpg)
![Screenshot_2020-08-21-19-24-51-789_com mi health](https://user-images.githubusercontent.com/69436116/90946329-66d3c700-e3f1-11ea-9896-fe7cccd4537d.jpg)
![Screenshot_2020-08-21-19-24-53-688_com mi health](https://user-images.githubusercontent.com/69436116/90946330-676c5d80-e3f1-11ea-9879-6a4d8f164d7a.jpg)
![Screenshot_2020-08-21-19-24-55-315_com mi health](https://user-images.githubusercontent.com/69436116/90946331-676c5d80-e3f1-11ea-8fd0-c36fb4a5a4bf.jpg)
![Screenshot_2020-08-21-19-24-59-107_com mi health](https://user-images.githubusercontent.com/69436116/90946332-6804f400-e3f1-11ea-972f-bb20e9183f41.jpg)

Gracias :)

**Comment by Alemancillo** [comment]
Translated. Issue can be closed.
