### ISSUE TITLE
Statusbar FC on MI9

### ISSUE THREAD

**Issue by ingbrzy** [ingbrzy/MA-XML-12-SPANISH#7]
seems your translation causes statusbar FC on cepheus.. 

`05-15 12:06:21.495  9927  9927 E AndroidRuntime: FATAL EXCEPTION: main
05-15 12:06:21.495  9927  9927 E AndroidRuntime: Process: com.android.systemui, PID: 9927
05-15 12:06:21.495  9927  9927 E AndroidRuntime: java.lang.IllegalStateException: Invalid tracker: plataforma
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.VelocityTrackerFactory.obtain(Unknown Source:76)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PanelView.initVelocityTracker(Unknown Source:11)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PanelView.onTouchEvent(Unknown Source:561)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.NotificationPanelView.onTouchEvent(Unknown Source:228)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PanelBar.onTouchEvent(Unknown Source:176)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.PhoneStatusBarView.onTouchEvent(Unknown Source:20)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(Unknown Source:86)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:38)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:495)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:309)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(Unknown Source:58)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(Unknown Source:309)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBarWindowView.dispatchTouchEvent(Unknown Source:308)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(Unknown Source:9)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(Unknown Source:25)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(Unknown Source:21)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:21)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(Unknown Source:10)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(Unknown Source:7)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:25)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(Unknown Source:4)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(Unknown Source:0)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(Unknown Source:2)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(Unknown Source:25)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(Unknown Source:63)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(Unknown Source:69)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(Unknown Source:34)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(Unknown Source:65)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(Unknown Source:202)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.os.MessageQueue.nativePollOnce(Native Method)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.os.MessageQueue.next(Unknown Source:17)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.os.Looper.loop(Unknown Source:67)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at android.app.ActivityThread.main(Unknown Source:98)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(Unknown Source:11)
05-15 12:06:21.495  9927  9927 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(Unknown Source:275)
05-15 12:06:21.500  9927  9927 D OOMEventManagerFK: checkEventAndDumpForJE: 0`

so check your translation and let me know when its fixed..

thanks

**Comment by nmercy-arg** [comment]
I think its fixed, can you check?
