### ISSUE TITLE
MiMix2S Versión 20.5.14 Algunas cosas por traducir

### ISSUE THREAD

**Issue by cisneros1992** [ingbrzy/MA-XML-12-SPANISH#8]
Hola os dejo alguna capturas de cosas que faltan por traducir.
Aquí un resumen:

- El control center no está traducido.
- Panel de permisos no está traducido en su totalidad.
- El gestor de instalación no está traducido.
- La sección de Backup and restore en ajustes no está traducida.
- La sección de Factory Reset en ajustes no está traducida.
- La sección de Cast en ajustes no está traducida.
- La traducción al español de "Tocar dos veces para apagar pantalla" está mal, esta opción que se encuentra en Ajustes/Pantalla de bloqueo lo que hace es activar la pantalla con doble toque cuando está apagada.
- La sección de Sonido y vibración en Ajustes tiene texto sin traducir.
- Traducción faltante en la sección de Pantalla de inicio en Ajustes.
- El título de Passwords & Security en Ajustes no está traducido.
- La sección Privacy protection en Ajustesno está traducida.
- El titulo Privacy en Ajustes no está traducido.
- La aplicación Reloj tiene algunos textos sin traducir.

Gracias por vuestro curro, un saludo!
![Screenshot_2020-05-18-17-34-14-150_com lbe security miui](https://user-images.githubusercontent.com/57541156/82235291-d0e05a00-9932-11ea-99c9-700cff871d96.jpg)
![Screenshot_2020-05-18-17-44-39-028_com miui packageinstaller](https://user-images.githubusercontent.com/57541156/82235295-d2118700-9932-11ea-886e-2e88aad944a7.jpg)
![Screenshot_2020-05-18-17-44-53-026_com miui packageinstaller](https://user-images.githubusercontent.com/57541156/82235296-d2118700-9932-11ea-8675-98170079cbfa.jpg)
![Screenshot_2020-05-18-17-49-05-465_com android settings](https://user-images.githubusercontent.com/57541156/82235298-d2aa1d80-9932-11ea-93ae-d4fa72ea966b.jpg)
![Screenshot_2020-05-18-17-49-14-614_com android settings](https://user-images.githubusercontent.com/57541156/82235300-d2aa1d80-9932-11ea-9bf7-87817c22e9bd.jpg)
![Screenshot_2020-05-18-17-49-26-793_com android settings](https://user-images.githubusercontent.com/57541156/82235301-d342b400-9932-11ea-8e77-63307553b7cd.jpg)
![Screenshot_2020-05-18-17-49-44-440_com android settings](https://user-images.githubusercontent.com/57541156/82235304-d342b400-9932-11ea-9cde-30b67a80514d.jpg)
![Screenshot_2020-05-18-17-50-27-846_com android settings](https://user-images.githubusercontent.com/57541156/82235306-d342b400-9932-11ea-8e15-51129997c9bc.jpg)
![Screenshot_2020-05-18-17-50-39-990_com android settings](https://user-images.githubusercontent.com/57541156/82235309-d3db4a80-9932-11ea-90fb-e6cfc178ab4f.jpg)
![Screenshot_2020-05-18-17-50-53-863_com miui home](https://user-images.githubusercontent.com/57541156/82235310-d3db4a80-9932-11ea-8256-f212ef0c38f7.jpg)
![Screenshot_2020-05-18-17-51-05-275_com miui home](https://user-images.githubusercontent.com/57541156/82235313-d473e100-9932-11ea-8343-7674f9bc0f5a.jpg)
![Screenshot_2020-05-18-17-51-39-232_com android settings](https://user-images.githubusercontent.com/57541156/82235315-d473e100-9932-11ea-8d03-d91797b1a5b7.jpg)
![Screenshot_2020-05-18-17-51-50-057_com miui securitycenter](https://user-images.githubusercontent.com/57541156/82235317-d50c7780-9932-11ea-803c-83857efd9787.jpg)
![Screenshot_2020-05-18-17-51-55-502_com android settings](https://user-images.githubusercontent.com/57541156/82235319-d50c7780-9932-11ea-92af-ca5b026f36ca.jpg)
![Screenshot_2020-05-18-17-52-24-764_com android settings](https://user-images.githubusercontent.com/57541156/82235320-d50c7780-9932-11ea-8f3a-9879a633678e.jpg)
![Screenshot_2020-05-18-17-53-34-796_com miui home](https://user-images.githubusercontent.com/57541156/82235321-d5a50e00-9932-11ea-876d-906ea09ee20d.jpg)
![Screenshot_2020-05-18-18-03-17-724_com android deskclock](https://user-images.githubusercontent.com/57541156/82235322-d5a50e00-9932-11ea-9547-64207c838a6a.jpg)

**Comment by nmercy-arg** [comment]
En la próxima release gran parte estará traducida.
