### ISSUE TITLE
Faltas de traducciones menores MI 9T Weekly 20.9.3

### ISSUE THREAD

**Issue by Priplio** [ingbrzy/MA-XML-12-SPANISH#85]
Hola, les dejo algunas pequeñas faltas de traducción en varias apps. Gracias

**La app: Seguridad**
Sin traducir: lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.9.3

![1599344966904](https://user-images.githubusercontent.com/69436116/92314546-ac21f800-ef9e-11ea-82bb-0eb60dbc62f6.jpg)
![1599344966859](https://user-images.githubusercontent.com/69436116/92314547-ad532500-ef9e-11ea-80e4-25dbccbf52cc.jpg)
![1599344966825](https://user-images.githubusercontent.com/69436116/92314548-ae845200-ef9e-11ea-807f-2e56e3f795fd.jpg)
![1599344966830](https://user-images.githubusercontent.com/69436116/92314549-afb57f00-ef9e-11ea-856c-552926dfac53.jpg)
**El de cámara en segundo plano también carece de traducción**
![1599344966835](https://user-images.githubusercontent.com/69436116/92314545-aaf0cb00-ef9e-11ea-8234-83d82052867a.jpg)

**La app: Galeria**
Sin traducir: lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.9.3

![1599345034691](https://user-images.githubusercontent.com/69436116/92314565-f1dec080-ef9e-11ea-9652-343f93bc8dcf.jpg)
![1599344966863](https://user-images.githubusercontent.com/69436116/92314564-f1dec080-ef9e-11ea-8b17-fcc23a576bc0.jpg)
![IMG_20200905_182353](https://user-images.githubusercontent.com/69436116/92314997-3f5e2c00-efa5-11ea-96c4-f5cf33384939.jpg)

**La app: Ajustes**
Sin traducir: lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.9.3

![1599344966868](https://user-images.githubusercontent.com/69436116/92314623-fe174d80-ef9f-11ea-9de5-28879699d01e.jpg)
![1599344966850](https://user-images.githubusercontent.com/69436116/92314624-feafe400-ef9f-11ea-97df-7f80a47f5618.jpg)
![1599344966889](https://user-images.githubusercontent.com/69436116/92314625-ffe11100-ef9f-11ea-9bb2-591b955a4539.jpg)
![IMG_20200905_173822](https://user-images.githubusercontent.com/69436116/92314628-0079a780-efa0-11ea-9dfd-50b42638088b.jpg)
![IMG_20200905_174411](https://user-images.githubusercontent.com/69436116/92314630-01aad480-efa0-11ea-9032-2bad0e323258.jpg)

**La app: Cámara**
Sin traducir: lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.9.3

![1599346172114](https://user-images.githubusercontent.com/69436116/92314662-6d8d3d00-efa0-11ea-84e3-b7653997e422.jpg)
![1599344966840](https://user-images.githubusercontent.com/69436116/92314663-6ebe6a00-efa0-11ea-92f4-239e3f0e349b.jpg)
![1599346172109](https://user-images.githubusercontent.com/69436116/92314660-6bc37980-efa0-11ea-98c0-d6ef929284f5.jpg)

**La app: Descargas**
Sin traducir: lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.9.3

![1599344966845](https://user-images.githubusercontent.com/69436116/92314689-d5438800-efa0-11ea-8f26-a157ea1abbbf.jpg)
![1599344966863](https://user-images.githubusercontent.com/69436116/92314690-d5dc1e80-efa0-11ea-99fb-e2cf4aa83dd8.jpg)
![1599344966854](https://user-images.githubusercontent.com/69436116/92314774-07a1b500-efa2-11ea-939c-642688d03f93.jpg)

**La app: SystemUI**
Sin traducir: lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.9.3

![1599344966899](https://user-images.githubusercontent.com/69436116/92314705-0c199e00-efa1-11ea-8ab6-948f45a5730d.jpg)

**La app: Temas**
Sin traducir: lo señalo en capturas.
Dispotivo: MI 9T
Build: Weekly 2.9.3

![1599344966883](https://user-images.githubusercontent.com/69436116/92314713-2d7a8a00-efa1-11ea-8413-3c527d23b5da.jpg)

Gracias :)

**Comment by deivids84** [comment]
Buenas,
A partir de hoy soy el responsable de la traducción al español. Reviso los errores comentados. Si deseas colaborar lo puedes hacer aquí: http://bit.ly/385HaRf
Muchas gracias por tu colaboración

**Comment by deivids84** [comment]
Traducción completada.
