### ISSUE TITLE
2.9.17 mi 10 umi

### ISSUE THREAD

**Issue by partebragas** [ingbrzy/MA-XML-12-SPANISH#86]
![IMG_20200923_145508](https://user-images.githubusercontent.com/40788593/94015214-dcde9b80-fdac-11ea-8b05-06598c166127.jpg)
![IMG_20200923_145407](https://user-images.githubusercontent.com/40788593/94015219-dea85f00-fdac-11ea-81ed-d79257e3a8c3.jpg)
![IMG_20200923_145228](https://user-images.githubusercontent.com/40788593/94015222-dea85f00-fdac-11ea-8af6-bc787663e2a2.jpg)
![IMG_20200923_145142](https://user-images.githubusercontent.com/40788593/94015224-df40f580-fdac-11ea-9291-7e69619b7bb8.jpg)

Te dejo aquí los casos que he encontrado.

Un saludo y muchas gracias por vuestro trabajo.

**Comment by deivids84** [comment]
Traducción completada
