### ISSUE TITLE
20.9.24 umi mi10

### ISSUE THREAD

**Issue by partebragas** [ingbrzy/MA-XML-12-SPANISH#87]
![Screenshot_2020-09-24-19-39-48-813_com miui home](https://user-images.githubusercontent.com/40788593/94180704-b6009200-fe9e-11ea-805e-67a39921d94a.jpg)
![Screenshot_2020-09-24-19-43-40-571_com android settings](https://user-images.githubusercontent.com/40788593/94180709-b6992880-fe9e-11ea-9d42-1674cf75fbad.jpg)
![IMG_20200924_220810](https://user-images.githubusercontent.com/40788593/94194846-8b203900-feb2-11ea-8f4c-64363fd217bc.jpg)
![IMG_20200924_220731](https://user-images.githubusercontent.com/40788593/94194849-8c516600-feb2-11ea-9ec7-5de1d9e2de0f.jpg)
![IMG_20200924_224111](https://user-images.githubusercontent.com/40788593/94198274-51056600-feb7-11ea-8c72-3371e24df563.jpg)

Un saludo y gracias

**Comment by partebragas** [comment]
![IMG_20200925_235433](https://user-images.githubusercontent.com/40788593/94319641-664bc480-ff8b-11ea-8c13-b0ffd01160c0.jpg)

**Comment by partebragas** [comment]
![Screenshot_2020-09-26-14-44-17-443_com android settings](https://user-images.githubusercontent.com/40788593/94341106-3215e980-0007-11eb-9a8a-16443b571be9.jpg)

**Comment by deivids84** [comment]
Traducción completada
