### ISSUE TITLE
20.10.16

### ISSUE THREAD

**Issue by partebragas** [ingbrzy/MA-XML-12-SPANISH#88]
![Screenshot_2020-10-19-01-43-39-173_com android thememanager](https://user-images.githubusercontent.com/40788593/96389966-9f560e00-11b2-11eb-98ec-d2f4487bcaee.jpg)
![Screenshot_2020-10-19-00-51-39-973_com google android setupwizard](https://user-images.githubusercontent.com/40788593/96389968-a11fd180-11b2-11eb-8704-a9ad61971b24.jpg)
![Screenshot_2020-10-19-00-41-18-141_com android settings](https://user-images.githubusercontent.com/40788593/96389969-a250fe80-11b2-11eb-992a-63f0764c7bc7.jpg)
![Screenshot_2020-10-19-00-41-09-432_com android settings](https://user-images.githubusercontent.com/40788593/96389971-a3822b80-11b2-11eb-8584-0e9cf53f2c63.jpg)
![Screenshot_2020-10-19-00-40-55-669_com android settings](https://user-images.githubusercontent.com/40788593/96389973-a54bef00-11b2-11eb-98ec-bc128016a305.jpg)
![Screenshot_2020-10-19-00-30-48-837_com android provision](https://user-images.githubusercontent.com/40788593/96389980-ab41d000-11b2-11eb-9d5f-205cf999ad58.jpg)
![Screenshot_2020-10-19-00-40-36-149_com android settings](https://user-images.githubusercontent.com/40788593/96389981-abda6680-11b2-11eb-8b5c-4c3ec7f6f7be.jpg)
![Screenshot_2020-10-19-00-40-11-690_com android settings](https://user-images.githubusercontent.com/40788593/96389983-ad0b9380-11b2-11eb-974e-f583ca376565.jpg)

**Comment by partebragas** [comment]
![Screenshot_2020-10-20-09-38-35-190_com android settings](https://user-images.githubusercontent.com/40788593/96555629-4ffa0580-12b8-11eb-8c5a-270270d063fe.jpg)
![Screenshot_2020-10-20-09-38-41-516_com android settings](https://user-images.githubusercontent.com/40788593/96555636-50929c00-12b8-11eb-8db4-78f6f354468e.jpg)
![Screenshot_2020-10-20-09-38-18-621_com android settings](https://user-images.githubusercontent.com/40788593/96555639-512b3280-12b8-11eb-8890-c9c8b6ba2717.jpg)

**Comment by deivids84** [comment]
Traducción completada
