### ISSUE TITLE
Fallo traducción No Molestar Mi10Pro Stable 12.1.3

### ISSUE THREAD

**Issue by rube13** [ingbrzy/MA-XML-12-SPANISH#90]
**La aplicación**: Ajustes > Sonido y vibración > No Molestar
**La frase que está la frase sin traducir o está mal escrita**: Indicada en la captura de pantalla
**El modelo de tú dispositivo**: Mi10Pro
**Versión de la ROM** (Stable/Weekly, y número de versión): Stable 12.1.3

![IMG_20201031_113037](https://user-images.githubusercontent.com/69046280/97777009-4c466880-1b6d-11eb-9a06-e7095779d05e.jpg)

**Comment by rube13** [comment]
No corregido en V12.2.1.0 STABLE

**Comment by deivids84** [comment]
Buenas,
A partir de hoy soy el responsable de la traducción al español. Reviso los errores comentados. Si deseas colaborar lo puedes hacer aquí: http://bit.ly/385HaRf
Muchas gracias por tu colaboración

**Comment by deivids84** [comment]
Traducción completada
