### ISSUE TITLE
Fallo traducción Temporizador No Molestar Mi10Pro Stable 12.1.3

### ISSUE THREAD

**Issue by rube13** [ingbrzy/MA-XML-12-SPANISH#91]
**La aplicación**: Ajustes > Sonido y vibración > No Molestar > Programar hora de activación > Añadir
**La frase que está la frase sin traducir o está mal escrita**: Indicada en la captura de pantalla
**El modelo de tú dispositivo**: Mi10Pro
**Versión de la ROM** (Stable/Weekly, y número de versión): Stable 12.1.3

![IMG_20201031_113012](https://user-images.githubusercontent.com/69046280/97777076-e9a19c80-1b6d-11eb-9a59-00aa69542dae.jpg)

**Comment by rube13** [comment]
No corregido en V12.2.1.0 STABLE

**Comment by deivids84** [comment]
Traducción completada
