### ISSUE TITLE
Fallo traducción Sonido y Vibración Mi10Pro Stable 12.1.3

### ISSUE THREAD

**Issue by rube13** [ingbrzy/MA-XML-12-SPANISH#92]
**La aplicación**: Ajustes > Sonido y vibración
**La frase que está la frase sin traducir o está mal escrita**: Indicada en la captura de pantalla
**El modelo de tú dispositivo**: Mi10Pro
**Versión de la ROM** (Stable/Weekly, y número de versión): Stable 12.1.3

![IMG_20201031_114134](https://user-images.githubusercontent.com/69046280/97777099-1f468580-1b6e-11eb-9fc0-45cf261fdaff.jpg)

**Comment by rube13** [comment]
No corregido en V12.2.1.0 STABLE

**Comment by deivids84** [comment]
Traducción completada
