### ISSUE TITLE
Default App Fail

### ISSUE THREAD

**Issue by carlospublisher** [ingbrzy/MA-XML-12-SPANISH#97]
Regardless of how many times I put an App as Default, the system always asks me which App I prefer to use.
![Screenshot_2021-01-07-14-14-39-967_android](https://user-images.githubusercontent.com/77122961/103934833-ac203900-50f3-11eb-8e90-bf347b55a2eb.jpg)

**Comment by deivids84** [comment]
Buenas,
Esto lo tendrás que comentar al foro, aquí solo problemas de traducción
Un saludo

**Comment by carlospublisher** [comment]
Genial, mil perdones. Gracias por responder!
