### ISSUE TITLE
21.1.6

### ISSUE THREAD

**Issue by texta84** [ingbrzy/MA-XML-12-SPANISH#98]
Antes que nada gracias por esta gran trabajo de traducción que están haciendo.
Hay algunas cadenas que aún aparecen sin traducción

Xiaomi Mi 9 (Cepheus) 21.1.6

![IMG_20210108_145826](https://user-images.githubusercontent.com/65029682/104063820-68e0cb80-51c2-11eb-9745-6a453d56af25.jpg)
![IMG_20210108_145746](https://user-images.githubusercontent.com/65029682/104063843-74cc8d80-51c2-11eb-8fa7-cf9ae24549b0.jpg)
![IMG_20210108_145607](https://user-images.githubusercontent.com/65029682/104063862-80b84f80-51c2-11eb-8a21-00414c512aa8.jpg)
![IMG_20210108_150500](https://user-images.githubusercontent.com/65029682/104064180-13f18500-51c3-11eb-9f71-f2df989ce785.jpg)
![IMG_20210108_150548](https://user-images.githubusercontent.com/65029682/104064208-1fdd4700-51c3-11eb-893b-b453a9527323.jpg)
![IMG_20210108_152822](https://user-images.githubusercontent.com/65029682/104066210-a3e4fe00-51c6-11eb-8c16-07cedb3c6fb2.jpg)
![IMG_20210108_152950](https://user-images.githubusercontent.com/65029682/104066236-ae9f9300-51c6-11eb-9f6d-ad3c7ad9f9e8.jpg)
![IMG_20210108_153030](https://user-images.githubusercontent.com/65029682/104066243-b2cbb080-51c6-11eb-9782-c076c8585bcf.jpg)
![IMG_20210108_153057](https://user-images.githubusercontent.com/65029682/104066252-b6f7ce00-51c6-11eb-9fac-c3132bdff533.jpg)

**Comment by deivids84** [comment]
![Screenshot_2021-01-08-23-45-29-197_com android settings](https://user-images.githubusercontent.com/13929105/104072575-d36a2980-520b-11eb-8b93-5372cb401034.jpg)
![Screenshot_2021-01-08-23-45-20-512_com android settings](https://user-images.githubusercontent.com/13929105/104072579-d6fdb080-520b-11eb-8427-698fe16dbd58.jpg)
![Screenshot_2021-01-08-23-44-32-167_com android settings](https://user-images.githubusercontent.com/13929105/104072584-da913780-520b-11eb-9eaf-35fbfcf65f53.jpg)
Esta todo traducido. Prueba en volver a instalar o cambiar el idioma y volver al Español

**Comment by texta84** [comment]
Ya intenté reinstalando, cambiando de idioma y volviendo al español, limpiando caché desde el recovery, cambiando entre español (España) y español (América) y sigue igual. Alguna otra sugerencia?

![IMG_20210108_175422](https://user-images.githubusercontent.com/65029682/104076104-9d608180-51da-11eb-827a-bc452951c2cd.jpg)

**Comment by deivids84** [comment]
Por alguna razón no se habrá aplicado las nuevas traducciones a la última beta de tu modelo.
