### ISSUE TITLE
Cadenas faltantes

### ISSUE THREAD

**Issue by texta84** [ingbrzy/MA-XML-12-SPANISH#99]
Revisando los paquetes que están disponibles veo que faltan algunas cadenas, por ejemplo en el paquete: **MA-XML-12-SPANISH/Spanish/device/cepheus/Settings.apk/res/values-es/strings.xml** no se encuentran cadenas que sí están en el paquete: **MA-XML-12-SPANISH/Spanish/main/Settings.apk/res/values-es/strings.xml** y no se si eso influya en las cadenas que faltan por traducir en mi Cepheus (Xiaomi Mi 9). Lo muestro gráficamente.

Xiaomi Mi 9 (Cepheus)

![Completo](https://user-images.githubusercontent.com/65029682/104096277-2a4e1e00-5261-11eb-9503-d1d218ca5d59.png)

![Faltante](https://user-images.githubusercontent.com/65029682/104096315-6d0ff600-5261-11eb-9c1f-3596cb8537c2.png)

**Comment by deivids84** [comment]
Buenas,
Debe de ser eso, voy a eliminar está carpeta device
Saludos

El ds., 9 de gen. 2021, 17:00, texta84 <notifications@github.com> va
escriure:

**Comment by texta84** [comment]
Esperemos que con eso se solucione. Gracias por responder y toda mi admiración por su gran trabajo.

**Comment by deivids84** [comment]
Confirmado, el Mi 9 tenía una traducción aparte la cual no actualizaba. He adaptado la traducción general para que no produzca fallos en el Mi 9 y en la siguiente beta ya estará solucionado. Muchas gracias por tu colaboración. 

Si quieres continuar colaborando para mejorar la traducción lo puedes hacer en el siguiente enlace [http://bit.ly/385HaRf](url)
